// ── Artifact Writer — validates and persists markdown output ────────────────

import { mkdir, writeFile } from 'node:fs/promises'
import { join } from 'node:path'
import type { LoopOutcome, DeliberationRound, IdeaCard, ScoreWeights } from '../data/types.js'
import type { EventConfig } from '../config/types.js'
import { mergeWeights } from '../data/scoring.js'

const ARTIFACTS = [
  'spec.md',
  'implementation-plan.md',
  'executive-summary.md',
  'shortlist.md',
  'evidence-dossier.md',
  'loop-log.md',
  'approval-sheet.md',
  'decision-brief.md',
] as const

export type ArtifactName = (typeof ARTIFACTS)[number]

/**
 * Write the full artifact set for a completed run.
 * Returns the list of written file paths.
 */
export async function writeArtifacts(
  config: EventConfig,
  outcome: LoopOutcome,
  allRounds: DeliberationRound[],
  evidenceDump: string,
): Promise<string[]> {
  const outDir = join(config.outputDir ?? 'output', config.slug)
  await mkdir(outDir, { recursive: true })

  const files: string[] = []
  const write = async (name: string, content: string) => {
    const path = join(outDir, name)
    await writeFile(path, content, 'utf-8')
    files.push(path)
  }

  await write('spec.md', renderSpec(config, outcome.winner))
  await write('implementation-plan.md', renderImplementationPlan(outcome))
  await write('executive-summary.md', renderExecutiveSummary(outcome))
  await write('shortlist.md', renderShortlist(outcome, config.weights))
  await write('evidence-dossier.md', evidenceDump)
  await write('loop-log.md', renderLoopLog(allRounds))
  await write('approval-sheet.md', renderApprovalSheet(outcome))
  await write('decision-brief.md', renderDecisionBrief(outcome, config.weights))

  return files
}

// ── Template renderers ─────────────────────────────────────────────────────

function renderSpec(config: EventConfig, winner: IdeaCard): string {
  return `# ${config.name} — Solution Spec

> Auto-generated by the Hackathon Strategist. The winning solution.

## 1. Elevator Pitch

${winner.oneLinePitch}

## 2. Problem Statement (verbatim)

${config.problemStatements.map((p) => `> ${p}`).join('\n\n')}

## 3. Target User

${winner.targetUser}

## 4. Prompt → Solution Fit

| Prompt asks for | What we build |
|---|---|
| ${config.problemStatements.map((p) => `| ${p} | ${winner.problemFit} |`).join('\n')}

## 5. The Differentiator

${winner.differentiator}

## 6. Tech Approach

${winner.techApproach}

## 7. Data Leverage

${winner.dataLeverage}

## 8. Gating Fit

${winner.gatingFit}

## 9. Build Scope

${winner.buildScope}

${winner.feasibility ? `
## 10. Feasibility Assessment

- Build window: ${winner.feasibility.buildWindowHours}h
- Estimated effort: ${winner.feasibility.effortHours}h
- Risk: ${winner.feasibility.risk}
- Planned cuts: ${winner.feasibility.cuts.map((c) => `- ${c}`).join('\n')}
` : ''}
`
}

function renderImplementationPlan(outcome: LoopOutcome): string {
  const top3 = outcome.top3.map((t, i) => `### ${i + 1}. ${t.oneLinePitch}\n\n${t.buildScope}`).join('\n\n')
  return `# Implementation Plan

> Auto-generated by the Hackathon Strategist.

## Recommended Winner

${outcome.winner.oneLinePitch}

**Why it wins:** selected by unanimous Reviewer Panel approval across ${outcome.rounds.length} deliberation round(s).

## Top 3

${top3}

## MVP Scope

${outcome.winner.buildScope}

## Definition of Done

- [ ] Core flow end-to-end
- [ ] The differentiator is visible and functional
- [ ] Deployed and demoable
`
}

function renderExecutiveSummary(outcome: LoopOutcome): string {
  const wordCount = outcome.winner.oneLinePitch.split(/\s+/).length
  const body = wordCount > 150
    ? outcome.winner.oneLinePitch.split(/\s+/).slice(0, 150).join(' ') + '…'
    : outcome.winner.oneLinePitch
  return `# Executive Summary

${body}
`
}

function renderShortlist(outcome: LoopOutcome, weights?: Partial<ScoreWeights>): string {
  const w = mergeWeights(weights)
  const lastRound = outcome.rounds[outcome.rounds.length - 1]
  const scores = lastRound?.scores ?? []

  const rows = outcome.top3.map((idea) => {
    const s = scores.find((sc) => sc.ideaId === idea.id)
    return `| ${idea.oneLinePitch} | ${s?.criteria.problemFit ?? '-'} | ${s?.criteria.feasibility ?? '-'} | ${s?.criteria.innovation ?? '-'} | ${s?.criteria.stakeholderAlignment ?? '-'} | ${s?.criteria.dataLeverage ?? '-'} | ${s?.criteria.demoAbility ?? '-'} | **${s?.total ?? '-'}** |`
  }).join('\n')

  return `# Shortlist — Top 3

| Idea | Problem Fit (×${w.problemFit}) | Feasibility (×${w.feasibility}) | Innovation (×${w.innovation}) | Stakeholder (×${w.stakeholderAlignment}) | Data (×${w.dataLeverage}) | Demo (×${w.demoAbility}) | Total |
|---|---|---|---|---|---|---|---|
${rows}
`
}

function renderLoopLog(rounds: DeliberationRound[]): string {
  return `# Deliberation Loop Log

${rounds.map((r) => `
## Round ${r.number}

### Debate
${r.debate.map((d) => `**${d.persona}:** ${d.text}\n\n*Sources: ${d.citations.join(', ')}*`).join('\n\n')}

### Scores
${r.scores.map((s) => `- **${s.ideaId}**: ${s.total.toFixed(3)} (rank ${s.rank ?? '-'})`).join('\n')}

### Verdicts
${r.verdicts.map((v) => `- **${v.reviewer}**: ${v.verdict.toUpperCase()}${v.feedback.length > 0 ? '\n' + v.feedback.map((f) => `  - ${f.topic}: ${f.issue} → ${f.requiredChange}`).join('\n') : ''}`).join('\n')}

### Revisions
${r.revisions.length > 0
  ? r.revisions.map((rev) => `- ${rev.feedbackId}: ${rev.whatChanged}`).join('\n')
  : '_No revisions this round._'}
`).join('\n---\n\n')}
`
}

function renderApprovalSheet(outcome: LoopOutcome): string {
  const rows = (Object.entries(outcome.approvals) as [string, boolean][]).map(
    ([persona, approved]) => `| ${persona} | ${approved ? '✅ APPROVED' : '❌ NOT APPROVED'} |`,
  ).join('\n')

  const dissents = outcome.dissentLog.length > 0
    ? outcome.dissentLog.map((d) => `- **${d.reviewer}**: ${d.objection}`).join('\n')
    : '_No dissents._'

  return `# Reviewer Approval Sheet

| Reviewer | Verdict |
|---|---|
${rows}

## Dissents

${dissents}
`
}

function renderDecisionBrief(outcome: LoopOutcome, weights?: Partial<ScoreWeights>): string {
  const w = mergeWeights(weights)
  const lastRound = outcome.rounds[outcome.rounds.length - 1]
  const scores = lastRound?.scores ?? []

  return `# Decision Brief

## Scoring Model

| Criterion | Weight |
|---|---|
| Problem–Solution Fit | ${(w.problemFit * 100).toFixed(0)}% |
| Feasibility | ${(w.feasibility * 100).toFixed(0)}% |
| Innovation / Differentiation | ${(w.innovation * 100).toFixed(0)}% |
| Stakeholder Alignment | ${(w.stakeholderAlignment * 100).toFixed(0)}% |
| Data Leverage | ${(w.dataLeverage * 100).toFixed(0)}% |
| Demo-ability | ${(w.demoAbility * 100).toFixed(0)}% |

## Final Scores

${scores.map((s) => `- **${s.ideaId}** (rank ${s.rank ?? '-'}): ${s.total.toFixed(3)}`).join('\n')}

## Runner-Up Flip Conditions

${outcome.top3.length >= 2
  ? `The runner-up (${outcome.top3[1].oneLinePitch}) could promote to winner if:
- The Judge scores its Innovation criterion ≥ 8/10 (currently ${scores.find((s) => s.ideaId === outcome.top3[1]?.id)?.criteria.innovation ?? '-'}), AND
- The Build Feasibility Reviewer confirms it can be built in under half the build window.`
  : '_Insufficient data for flip analysis._'}

## Outcome

${outcome.status === 'approved'
  ? `Unanimous approval after ${outcome.rounds.length} round(s).`
  : `Escalated after ${outcome.rounds.length} round(s) — iteration budget exhausted.`}
`
}
